server:
  port: 1000

encrypt:
  key: ${QUIZ_ME_UP_ENCRYPT_KEY}

springdoc:
  swagger-ui:
    use-root-path: true

spring:
  application:
    name: configuration-server-application
  profiles:
    active: local, native
  cloud:
    config:
      server:
        prefix: /configuration
        native:
          search-locations: classpath:/local
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: production
  cloud:
    config:
      server:
        git:
          default-label: master
          username: '{cipher}955945e00477700b2956db55415d711116d4e1c260dac4bcef849f6c9e72418b'
          password: '{cipher}25607a7323431f150534bb2f1e7210c31289a2a679f3182dd0800b3bbf592e4b3848b66c3925121b3daaca6ae29b3148279f490f4546cec78f047dca73101019'
          uri: https://github.com/quiz-me-up/configuration-repository