server:
  port: 1000

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080