---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quizmeup-configuration-server-development-autoscaler
  namespace: quizmeup-development
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quizmeup-configuration-server-development-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60