spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo-database