server:
  port: 0


spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:5000
      client:
        registration:
          server:
            provider: spring
            client-id: server
            client-name: server
            client-secret: '{cipher}25b98bf2c0db229afdad5e62df2cf441b0b45e86f317137c22842bcb092f667d'
            authorization-grant-type: client_credentials
            scope:
              - read
              - write
        provider:
          spring:
            token-uri: http://localhost:5000/oauth2/token
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: server

management:
  endpoint:
    env:
      show-values: ALWAYS
    metrics:
      enable: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/

quizmeup:
  security:
    enabled: true
    unprotected-path:
      - /
      - /error
      - /favicon.ico
      - /*/*.png
      - /*/*.gif
      - /*/*.svg
      - /*/*.jpg
      - /*/*.html
      - /*/*.css
      - /*/*.js
      - /*/*.js.map
      - /actuator/**
      - /v3/api-docs
      - /v3/api-docs/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger-ui/**
      - /webjars/**
      - /assets/**
      - /csrf
      - /oauth/**
      - /oauth2/**
      - /login
      - /logout

logging:
  level:
    org.mongodb: ERROR
    io.github.quizmeup: DEBUG
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR
    org.springframework.context.support: ERROR
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.springframework.cloud: ERROR
    org.springframework.boot: ERROR
    org.springframework.amqp.rabbit: ERROR
    org.springframework.data.convert.CustomConversions: ERROR
