name: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.QUIZ_ME_UP_GITHUB_TOKEN }}
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: next_version
        uses: quiz-me-up/reusable-workflow/.github/actions/next-version@master
        with:
          release_type: ${{ github.event.inputs.release_type }}
          fallback_version: '0.0.0'

      - name: Setup java-maven
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-java-maven@master

      - name: Update pom.xml versions
        run: |
          mvn versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -DprocessAllModules=true -DgenerateBackupPoms=false -DremoveSnapshot=true

      - name: Maven build command execution
        run: mvn clean install

      - name: Publish docker image to docker hub
        uses: quiz-me-up/reusable-workflow/.github/actions/publish-docker-image@master
        with:
          image_name: configuration-server
          image_tag: ${{ steps.next_version.outputs.version }}
          dockerhub_username: ${{ secrets.QUIZ_ME_UP_DOCKER_USERNAME }}
          dockerhub_token: ${{ secrets.QUIZ_ME_UP_DOCKER_TOKEN }}
          encrypt_key: ${{ secrets.QUIZ_ME_UP_ENCRYPT_KEY }}
          spring_profiles: production,docker

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.QUIZ_ME_UP_GITHUB_TOKEN }}
          tag: ${{ steps.next_version.outputs.full_version }}

      - name: Setup git bot user
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-git-bot-user@master

      - name: Create Tag
        run: |
          git add .
          git commit --allow-empty -m "release ${{ steps.next_version.outputs.full_version }}"
          git tag -a ${{ steps.next_version.outputs.full_version }} -m "ci : release ${{ steps.next_version.outputs.full_version }}"
          git push origin master --follow-tags

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.next_version.outputs.full_version }}
          name: Release ${{ steps.next_version.outputs.full_version }}
          body: ${{ steps.changelog.outputs.changes }}